### ISSUE TITLE
Archer C2300 v2.0

### ISSUE THREAD

**Issue by ColinRobbins** [ericpignet/home-assistant-tplink_router#13]
Hello,
I've tried to use this integration with an Archer C2300 v2.0.
It fails at the login stage.
Any suggestions?

**Comment by kwirk** [comment]
I have a similar router (C1200 model) which is working. Did you use the encrypted version of the password, per instructions in [README](https://github.com/ericpignet/home-assistant-tplink_router/blob/master/README.md).

**Comment by ColinRobbins** [comment]
Thanks @kwirk, it good to know it works with the C1200, as the principles should be similar.
I have tried the encrypted password, and have started to try and debug.
It seems there is some kind of challenge/response mechanism.
When I look at `document.getElementById("login-password").value;` it changes every time a password is entered, even if the password is identical.

**Comment by Electry** [comment]
I did some digging and managed to implement the auth. mechanism for the C2300 in python.

Initially it requests two public RSA keys (seem to be unique to each device), one to encrypt the password, the other to encrypt the signature. Then, it generates a random AES key which is sent to the router as a part of the signature, and is used later for encrypting/decrypting the data body of each subsequent http request/response (essentially for end-to-end encrypted communication).

Looks like they upgraded their security in later devices/firmwares, since no device supported here seems to have E2E.

I made it into a similar home assistant device tracker integration if anyone is interested: https://github.com/Electry/TPLink-C2300-HASS

**Comment by ColinRobbins** [comment]
Thanks for this,  I've tried it in my test environment at it works as described.
I run HA in a Python venv, so needed to run
```
pip3 install pycryptodome
```
in the venv first, to load the libraries.

The challenge I now have is I currently use `nmap_tracker` and have a number of GUI and Automations elements configured, but using the TPLink all the entity names change.  So I've got a fair chunk of updating needed.

**Comment by ColinRobbins** [comment]
Having to put the Firewall password in the `secrets.yaml` file is something of a worry.
If someone breaks into my Linux box, they can then get access to my router, giving them the option to move laterally.
On the other hand, if they got my Linux machine, I probably pwned anyway, so does it really increase the risk?
I'd welcome others views on this.

**Comment by ColinRobbins** [comment]
Timed out
