### ISSUE TITLE
Login with email and password

### ISSUE THREAD

**Issue by GuyKh** [ericpignet/home-assistant-tplink_router#2]
Using VR600.
The home of my router is accepting only email and password..

Using it doesn't seems to be working.
How do I switch to username/password (not TPLink account) login?

**Comment by ericpignet** [comment]
Hi,
I've only repackaged the old TP-Link router integration in HACS, so that people can keep using it even though it was officially removed from Home Assistant. I've only implemented support for the N600, which is my own router.
I don't have a VR600 so I can't troubleshoot and fix by myself.

If you are able to find out how authentication works for your router, and ideally what HTTP requests are needed to get to the page with the list of MAC addresses of currently connected devices, I'm happy to integrate in the code.

Eric

**Comment by GuyKh** [comment]
I'd be happy to help. Could you create a snippet for me to run or point me where it's done?

**Comment by ericpignet** [comment]
Hi GuyKh,
I don't think this can be investigated with just a snippet to run.
When I added support for my router (N600), I used Chrome developer mode to capture the HTTP queries required to authenticate, and to get the page of connected devices.
Eric

**Comment by GuyKh** [comment]
After a s**tload of work, got a running python script which does exactly this (and thanks for Chrome DevTools!)

https://gist.github.com/GuyKh/545ebfe1e95f48a8c623cf959cebb82b

**Comment by GuyKh** [comment]
#4

**Comment by ericpignet** [comment]
Well done with the router support. The encryption of the username/password with a public key lost in the middle of another page must have required a lot of javascript debugging of the login process ;)
I'm closing the issue. Normally you can upgrade to 0.0.3 from HACS.
